name: sendto
on:
  schedule:
  - cron:  '0 15 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send to friend

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ env.GITHUB_REF_NAME }}

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./main.py

    env:
      APP_ID: ${{ secrets.APP_ID }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
      USER_ID: ${{ secrets.USER_ID }}
      CITY: ${{ secrets.CITY }}
      NAME: ${{ secrets.NAME }}
